### PR TITLE
Features

### PR DESCRIPTION
**Pull request by maltegrosse**
Hi, added some features, please review and test it against the current version.
(refers to #15 #16 #13 )

- switched all admin routes to /admin/... 
- auto redirect from ./ to ./admin
- enabled two auth flows (admin and update)
- disabled auth for admin by skipping env variable DDNS_ADMIN_LOGIN
- introduced optional env variable DDNS_TITLE for dynamic UI title (default TheBBCloudDynDNS)
- set copyright date in footer dynamic on startup
- moved all remote js/css packages into static in order to avoid external dependencies
- added "copy to clipboard button" on host overview page
- replaced all fmt.Println by log...
- introduced new optional env variable DDNS_CLEAR_LOG_INTERVAL to clear logs after n days (int). (check runs daily once if update request received)
- newest logs are shown from top to bottom on logs page (newest first)
- added multiarch github workflow

### CODE REVIEW

**Comment by benjaminbear** [comment]
Awesome, thank you for contributing, will review the next days!

**Comment by maltegrosse** [comment]
thank you. let me know if there are any issues.

Some side notes: I see some general issues using [h.AutHost](https://github.com/benjaminbear/docker-ddns-server/blob/master/dyndns/handler/handler.go#L17), during the dns update process, as h is only instantiated [once](https://github.com/benjaminbear/docker-ddns-server/blob/master/dyndns/main.go#L32) for the whole application. It could likely cause some conflicts if parallel requests appear. 
With the current implementation it is even more likely, as an admin login resets the h.AuthHost too.

Perhaps better forward the host data via meta data. The echo context provides a [Set&Get](https://github.com/labstack/echo/blob/master/context.go#L97) for this: (untested)
`c.Set("host",host )` in auth method
and later in the [update ](https://github.com/benjaminbear/docker-ddns-server/blob/master/dyndns/handler/host.go#L225 )method
`host:= c.Get("host")`

**Comment by maltegrosse** [comment]
I added two more things.
1. switched to c.get & c.set and removed h.AuthHost - as described above
2. added additional auth checks for update as it was possible to bypass authentication somehow with valid usr/pw but different host

**Comment by maltegrosse** [comment]
@benjaminbear I want to enable automatically *.subdomain.ddns.domain.tld

Do you see any issue by just adding a second line:
`w.WriteString(fmt.Sprintf("update add %s.%s %v %s %s\n", hostname, zone, ttl, addrType, target))`

and (*.%s...)

`w.WriteString(fmt.Sprintf("update add *.%s.%s %v %s %s\n", hostname, zone, ttl, addrType, target))`

**Comment by maltegrosse** [comment]
okay, I think done for now :) -> added the wildcard option. you can also just pull my latest docker: `docker pull maltegrosse/docker-ddns-server:1.0.1` to test the changes.

**Comment by benjaminbear** [comment]
Wow, seems like you made a lot of changes. I'm on it :)

**Comment by maltegrosse** [comment]
added a final small feature: a logout url can be given - helpful for e.g. oauth signout urls

**Comment by ebelmxi** [comment]
@maltegrosse this is really awesome, thanks for your work :+1: 
I am absolutely not familiar with go therefore cannot review all the changes. However, I have build the image based on your repo and can't find any bugs on first look.

Would be great if the changes merged soon.

**Comment by maltegrosse** [comment]
@benjaminbear anything blocking the PR ? or anything I can help merging it?

**Comment by benjaminbear** [comment]
Thank you for your effort!

**Pull request merged**
